services:
  frontend:
    build:
      context: ./Frontend
    command: streamlit run main.py --server.port=${STREAMLIT_SERVER_PORT:-8501} --server.address=0.0.0.0
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:${STREAMLIT_SERVER_PORT:-8501}"
    volumes:
      - ./Frontend:/app
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    command: uvicorn app.main:app --reload --host=0.0.0.0 --port=${BACKEND_PORT:-8000}
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env