from decouple import AutoConfig

config = AutoConfig()

DATA_CREATE = config("DATA_CREATE")
GET_USERDATA_ALL = config("GET_USERDATA_ALL")
GET_USERDATA_EXPENSE = config("GET_USERDATA_EXPENSE")
GET_USERDATA_INCOME = config("GET_USERDATA_INCOME")
GET_EXPENSE_RANKING = config("GET_EXPENSE_RANKING")
GET_EXPENSE_DETAILS = config("GET_EXPENSE_DETAILS")




