[streamlit]
STREAMLIT_SERVER_PORT = 8501
BACKEND_PORT = 8000


# 로컬용 st.secrets
[api]
GET_EXPENSE_RANKING = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/expense/ranking/"
GET_EXPENSE_DETAILS = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/expense/details/"
GET_ANNUAL_EXPENSE_RANK = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/expense/annual"
GET_USERDATA_EXPENSE = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/expense/"

GET_USERDATA_INCOME = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/income/"
GET_INCOME_RANKING = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/income/ranking/"
GET_ANNUAL_INCOME_RANK = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/income/annual"

DATA_CREATE = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/create/"
UPDATE_USERDATA = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/update/"
DELETE_DATA = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/delete/"

GET_TOTAL_ASSETS = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/total_asset/"
GET_ALL_DATA = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/all_data/"
GET_EXPENSE_INCOME_LINE_GRAPH_DATA = "https://ab34-2001-2d8-e4b5-6c4f-1c29-45e5-5421-75ec.ngrok-free.app/userdata/bar_graph/"